import React, { useState } from 'react';

export const FAQSection: React.FC = () => {
  const [openIdx, setOpenIdx] = useState<number | null>(0);

  const faqs = [
    {
      q: 'How does Digital Vargani replace paper receipt books?',
      a: 'Volunteers use the mobile app to enter donor details and amount. The system instantly generates a digital slip with a unique serial number and sends it via WhatsApp, eliminating manual writing and physical book tracking.'
    },
    {
      q: 'Does the app work offline?',
      a: 'Yes. The Member App is designed with an offline-first architecture. You can generate slips even without an internet connection in crowded areas. The app automatically syncs the data to the central server once connectivity is restored.'
    },
    {
      q: 'How do mandal admins track collections?',
      a: 'Admins have access to a real-time dashboard showing total collection, member-wise tally, and recent transactions. You can also view trends compared to previous days or years.'
    },
    {
      q: 'Can we configure our own receipt template?',
      a: 'Absolutely. Mandal Admins can upload their logo, set custom header/footer text, and choose local language options (e.g., Marathi) for the digital receipts generated by the system.'
    },
    {
      q: 'Is donor data secure?',
      a: 'Yes, donor data is securely stored on cloud servers. We implement strict role-based access control, meaning volunteers only see their own collections, and only authorized admins can access the full mandal database.'
    }
  ];

  return (
    <section className="py-24 bg-[var(--surface-50)] border-y border-[var(--surface-200)]">
      <div className="container-max max-w-3xl">
        <div className="text-center mb-16">
          <h2 className="font-headline-md text-[var(--charcoal-900)] mb-4">
            Common questions
          </h2>
          <p className="font-body-lg text-[var(--charcoal-600)]">
            Everything you need to know about adopting Digital Mandal.
          </p>
        </div>

        <div className="space-y-4">
          {faqs.map((faq, idx) => {
            const isOpen = openIdx === idx;
            return (
              <div 
                key={idx} 
                className={`bg-white border rounded-2xl overflow-hidden transition-all duration-300 ${
                  isOpen ? 'border-[var(--festival-orange-subtle)] saas-shadow' : 'border-[var(--surface-200)] hover:border-[var(--surface-200)]'
                }`}
              >
                <button
                  onClick={() => setOpenIdx(isOpen ? null : idx)}
                  className="w-full px-6 py-5 text-left flex justify-between items-center bg-white outline-none"
                >
                  <span className={`font-headline-sm text-base ${isOpen ? 'text-[var(--festival-orange-hover)]' : 'text-[var(--charcoal-900)]'}`}>
                    {faq.q}
                  </span>
                  <span className={`material-symbols-outlined text-[var(--charcoal-400)] transition-transform duration-300 ${isOpen ? 'rotate-180 text-[var(--festival-orange)]' : ''}`}>
                    expand_more
                  </span>
                </button>
                
                <div 
                  className={`px-6 overflow-hidden transition-all duration-300 ease-in-out ${
                    isOpen ? 'max-h-[500px] pb-6 opacity-100' : 'max-h-0 opacity-0'
                  }`}
                >
                  <p className="font-body-md text-[var(--charcoal-600)] leading-relaxed">
                    {faq.a}
                  </p>
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
};
